### ISSUE TITLE
Duplicate Usage Map 1 feature

### ISSUE THREAD

**Issue by jameshunt8082** [jameshunt8082/CSR#10]
duplicate.
Any questions leave in github

**Comment by lkthecool** [comment]
This map is quite simple 

Col A - First row or cell A3 has a date (start date, if you want to see everything after may change it to 1st of may 2018). It will have impact on next 365 days and that will be calculated based on that.
Col B - Week number (In case you want to know week availability, you can apply filter use the week number.
Col C to G - Caravan type, 'A' means available and it has Green Color.
                                          'B' means booked and it has Grey Color.
Col H - Same for festivals, 'Fest' if the date has festival in it should be in grey color.
Col I - Availability ( number of caravans available, it has color scale)
