### ISSUE TITLE
Condition - needed as when caravan is not available BUT other are available AND the mileage is over

### ISSUE THREAD

**Issue by jameshunt8082** [jameshunt8082/CSR#7]
I noticed that customer Yetti had a delivery that was greater than 100 miles away.  yet the email chosen was NOT correct for that condition.   I think maybe because the caravan was not available but another caravan was available.  and once that condition is met it does NOT go on to check.

**Comment by jameshunt8082** [comment]
I made it over complicated.
We just need to use over 100 miles as a condition. (Can we for now remove the time condition)
1 hour
50 miles
2 hours
let us just use 100 miles.
BUT
if over 100 miles if caravan is available
if voer 100 milles AND caravan is not availabel but alternative caravan is available.

**Comment by lkthecool** [comment]
There are some google docs (templates), code is checking for condition and then choosing the correct template to create email draft.
Here after choosing the correct template, code has some incorrect steps, which forces to select the default template again (only for the hours and miles condition).
I have removed this line now and everything should work fine.
Advise : Please test the row 251, with other condition as well, like changing miles and hours etc.
